const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'src');
const componentsDir = path.join(srcDir, 'components');
const pagesDir = path.join(srcDir, 'pages');

if (!fs.existsSync(pagesDir)) {
  fs.mkdirSync(pagesDir, { recursive: true });
}
if (!fs.existsSync(componentsDir)) {
  fs.mkdirSync(componentsDir, { recursive: true });
}

const files = {
  // --- COMPONENTS ---
  'components/Hero.jsx': `import React from 'react';\nimport './Hero.css';\n\nconst Hero = () => {\n  return (\n    <section className="hero">\n      <div className="container hero-container">\n        <div className="hero-content">\n          <h1>Real Projects.<br/><span className="text-secondary">Real Skills.</span><br/>Real Opportunities.</h1>\n          <p>Connect with top companies, build real-world projects, and showcase your skills to land your dream job.</p>\n          <div className="hero-actions">\n            <button className="btn btn-primary">Find Projects</button>\n            <button className="btn btn-outline">Post a Project</button>\n          </div>\n        </div>\n        <div className="hero-image">\n          <div className="dashboard-mockup">\n            <div className="mockup-header"></div>\n            <div className="mockup-body">\n              <div className="mockup-sidebar"></div>\n              <div className="mockup-content">\n                <div className="mockup-cards">\n                  <div className="mockup-card"></div>\n                  <div className="mockup-card"></div>\n                  <div className="mockup-card"></div>\n                </div>\n                <div className="mockup-chart"></div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>\n  );\n};\n\nexport default Hero;`,
  'components/Hero.css': `.hero {\n  padding: 8rem 0;\n  background: linear-gradient(to right, var(--background), #e2e8f0);\n}\n.hero-container {\n  display: flex;\n  align-items: center;\n  gap: 4rem;\n}\n.hero-content {\n  flex: 1;\n}\n.hero-content h1 {\n  font-size: 4rem;\n  line-height: 1.1;\n  font-weight: 800;\n  color: var(--primary);\n  margin-bottom: 1.5rem;\n}\n.hero-content h1 .text-secondary {\n  color: var(--secondary);\n}\n.hero-content p {\n  font-size: 1.25rem;\n  color: var(--text-secondary);\n  margin-bottom: 2.5rem;\n  max-width: 500px;\n}\n.hero-actions {\n  display: flex;\n  gap: 1rem;\n}\n.hero-image {\n  flex: 1;\n}\n.dashboard-mockup {\n  background-color: var(--surface);\n  border-radius: var(--radius-lg);\n  box-shadow: var(--shadow-lg);\n  border: 1px solid var(--border);\n  height: 400px;\n  display: flex;\n  flex-direction: column;\n  overflow: hidden;\n}\n.mockup-header {\n  height: 50px;\n  border-bottom: 1px solid var(--border);\n  background-color: #f8fafc;\n}\n.mockup-body {\n  display: flex;\n  flex: 1;\n}\n.mockup-sidebar {\n  width: 80px;\n  background-color: var(--primary);\n}\n.mockup-content {\n  flex: 1;\n  padding: 1.5rem;\n  display: flex;\n  flex-direction: column;\n  gap: 1.5rem;\n}\n.mockup-cards {\n  display: flex;\n  gap: 1rem;\n}\n.mockup-card {\n  flex: 1;\n  height: 80px;\n  background-color: var(--background);\n  border-radius: var(--radius-md);\n}\n.mockup-chart {\n  flex: 1;\n  background-color: var(--background);\n  border-radius: var(--radius-md);\n}\n@media (max-width: 768px) {\n  .hero-container {\n    flex-direction: column;\n    text-align: center;\n  }\n  .hero-content p {\n    margin: 0 auto 2.5rem;\n  }\n  .hero-actions {\n    justify-content: center;\n  }\n}`,

  'components/HowItWorks.jsx': `import React from 'react';\nimport './HowItWorks.css';\n\nconst HowItWorks = () => {\n  return (\n    <section className="section bg-light" id="how-it-works">\n      <div className="container">\n        <h2 className="section-title">How SkillBridge Works</h2>\n        <div className="grid grid-3">\n          <div className="step-card">\n            <div className="step-number">1</div>\n            <h3>Company Posts</h3>\n            <p>Companies list real-world projects they need help with.</p>\n          </div>\n          <div className="step-card">\n            <div className="step-number">2</div>\n            <h3>Student Applies</h3>\n            <p>Students apply with their portfolio and pitch.</p>\n          </div>\n          <div className="step-card">\n            <div className="step-number">3</div>\n            <h3>Project Completed</h3>\n            <p>Get selected, do the work, and get reviewed.</p>\n          </div>\n        </div>\n      </div>\n    </section>\n  );\n};\n\nexport default HowItWorks;`,
  'components/HowItWorks.css': `.bg-light {\n  background-color: var(--surface);\n}\n.step-card {\n  background-color: var(--background);\n  padding: 2.5rem;\n  border-radius: var(--radius-lg);\n  text-align: center;\n  transition: transform 0.3s ease;\n}\n.step-card:hover {\n  transform: translateY(-5px);\n}\n.step-number {\n  width: 50px;\n  height: 50px;\n  background-color: var(--accent);\n  color: var(--primary);\n  border-radius: 50%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  font-size: 1.5rem;\n  font-weight: 700;\n  margin: 0 auto 1.5rem;\n}\n.step-card h3 {\n  margin-bottom: 1rem;\n  color: var(--primary);\n}`,

  'components/Categories.jsx': `import React from 'react';\nimport './Categories.css';\n\nconst Categories = () => {\n  return (\n    <section className="section" id="categories">\n      <div className="container">\n        <h2 className="section-title">Explore Categories</h2>\n        <div className="grid grid-3 categories-grid">\n          <div className="category-card">Web Development</div>\n          <div className="category-card">Graphic Design</div>\n          <div className="category-card">Social Media</div>\n          <div className="category-card">Content Writing</div>\n          <div className="category-card">Data Work</div>\n          <div className="category-card">Video Editing</div>\n        </div>\n      </div>\n    </section>\n  );\n};\n\nexport default Categories;`,
  'components/Categories.css': `.category-card {\n  background-color: var(--surface);\n  border: 1px solid var(--border);\n  padding: 2rem;\n  border-radius: var(--radius-md);\n  text-align: center;\n  font-weight: 600;\n  color: var(--primary);\n  cursor: pointer;\n  transition: all 0.2s ease;\n}\n.category-card:hover {\n  border-color: var(--secondary);\n  background-color: var(--secondary);\n  color: white;\n}`,

  'components/WhySkillBridge.jsx': `import React from 'react';\nimport './WhySkillBridge.css';\n\nconst WhySkillBridge = () => {\n  return (\n    <section className="section bg-light" id="why-skillbridge">\n      <div className="container">\n        <h2 className="section-title">Why SkillBridge?</h2>\n        <div className="grid grid-3">\n          <div className="feature-card">\n            <div className="feature-icon">\n              <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">\n                <path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"></path>\n                <path d="M12 12v9"></path>\n                <path d="m8 17 4 4 4-4"></path>\n              </svg>\n            </div>\n            <h3>Real Experience</h3>\n            <p>Work on actual projects that matter, not just sandbox tutorials.</p>\n          </div>\n          <div className="feature-card">\n            <div className="feature-icon">\n              <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">\n                <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path>\n                <circle cx="9" cy="7" r="4"></circle>\n                <path d="M22 21v-2a4 4 0 0 0-3-3.87"></path>\n                <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>\n              </svg>\n            </div>\n            <h3>Direct Connections</h3>\n            <p>Get noticed by top companies actively looking for talent.</p>\n          </div>\n          <div className="feature-card">\n            <div className="feature-icon">\n              <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">\n                <path d="M4 22h14a2 2 0 0 0 2-2V7.5L14.5 2H6a2 2 0 0 0-2 2v4"></path>\n                <polyline points="14 2 14 8 20 8"></polyline>\n                <path d="m3 15 2 2 4-4"></path>\n              </svg>\n            </div>\n            <h3>Build Portfolio</h3>\n            <p>Showcase completed work and verified reviews on your profile.</p>\n          </div>\n        </div>\n      </div>\n    </section>\n  );\n};\n\nexport default WhySkillBridge;`,
  'components/WhySkillBridge.css': `.feature-card {\n  background-color: var(--background);\n  padding: 2.5rem;\n  border-radius: var(--radius-md);\n  text-align: center;\n}\n.feature-icon {\n  font-size: 3rem;\n  margin-bottom: 1rem;\n}\n.feature-card h3 {\n  margin-bottom: 1rem;\n  color: var(--primary);\n}`,

  'components/FeaturedProjects.jsx': `import React from 'react';\nimport './FeaturedProjects.css';\n\nconst FeaturedProjects = () => {\n  return (\n    <section className="section" id="featured-projects">\n      <div className="container">\n        <h2 className="section-title">Featured Projects</h2>\n        <div className="grid grid-3">\n          <div className="project-card">\n            <div className="project-header">\n              <span className="badge">Web Dev</span>\n              <span className="status">Open</span>\n            </div>\n            <h3>E-commerce Frontend Refactor</h3>\n            <p className="company-name">TechStart Inc.</p>\n            <p className="project-desc">Looking for a React developer to modernize our product listing pages.</p>\n            <button className="btn btn-primary w-full">View Details</button>\n          </div>\n          <div className="project-card">\n            <div className="project-header">\n              <span className="badge">Design</span>\n              <span className="status">Open</span>\n            </div>\n            <h3>Brand Identity Redesign</h3>\n            <p className="company-name">Creative Studio</p>\n            <p className="project-desc">Need a fresh logo and brand guidelines for a new SaaS product.</p>\n            <button className="btn btn-primary w-full">View Details</button>\n          </div>\n          <div className="project-card">\n            <div className="project-header">\n              <span className="badge">Data</span>\n              <span className="status">Open</span>\n            </div>\n            <h3>Customer Data Analysis</h3>\n            <p className="company-name">Growth Metrics</p>\n            <p className="project-desc">Analyze Q3 user engagement data and present actionable insights.</p>\n            <button className="btn btn-primary w-full">View Details</button>\n          </div>\n        </div>\n      </div>\n    </section>\n  );\n};\n\nexport default FeaturedProjects;`,
  'components/FeaturedProjects.css': `.project-card {\n  background-color: var(--surface);\n  border: 1px solid var(--border);\n  padding: 2rem;\n  border-radius: var(--radius-lg);\n  box-shadow: var(--shadow-sm);\n  transition: box-shadow 0.2s ease;\n}\n.project-card:hover {\n  box-shadow: var(--shadow-md);\n}\n.project-header {\n  display: flex;\n  justify-content: space-between;\n  margin-bottom: 1.5rem;\n}\n.badge {\n  background-color: var(--secondary);\n  color: white;\n  padding: 0.25rem 0.75rem;\n  border-radius: var(--radius-full);\n  font-size: 0.875rem;\n  font-weight: 500;\n}\n.status {\n  color: var(--success);\n  font-weight: 500;\n  font-size: 0.875rem;\n}\n.project-card h3 {\n  font-size: 1.25rem;\n  margin-bottom: 0.5rem;\n  color: var(--primary);\n}\n.company-name {\n  color: var(--text-secondary);\n  font-weight: 500;\n  margin-bottom: 1rem;\n}\n.project-desc {\n  margin-bottom: 1.5rem;\n  font-size: 0.95rem;\n}\n.w-full {\n  width: 100%;\n}`,

  'components/Benefits.jsx': `import React from 'react';\nimport './Benefits.css';\n\nconst Benefits = () => {\n  return (\n    <section className="section bg-light" id="benefits">\n      <div className="container">\n        <h2 className="section-title">Mutual Benefits</h2>\n        <div className="grid grid-2">\n          <div className="benefit-box student-benefit">\n            <h3>For Students</h3>\n            <ul>\n              <li><span className="check-icon">✓</span> Gain practical, hands-on experience</li>\n              <li><span className="check-icon">✓</span> Earn money while learning</li>\n              <li><span className="check-icon">✓</span> Build a professional network</li>\n              <li><span className="check-icon">✓</span> Transition directly into full-time roles</li>\n            </ul>\n          </div>\n          <div className="benefit-box company-benefit">\n            <h3>For Companies</h3>\n            <ul>\n              <li><span className="check-icon">✓</span> Access fresh, motivated talent</li>\n              <li><span className="check-icon">✓</span> Get projects done efficiently</li>\n              <li><span className="check-icon">✓</span> Evaluate candidates on real work</li>\n              <li><span className="check-icon">✓</span> Reduce hiring risk and costs</li>\n            </ul>\n          </div>\n        </div>\n      </div>\n    </section>\n  );\n};\n\nexport default Benefits;`,
  'components/Benefits.css': `.benefit-box {\n  background-color: var(--surface);\n  padding: 3rem;\n  border-radius: var(--radius-lg);\n  border: 1px solid var(--border);\n}\n.benefit-box h3 {\n  font-size: 1.5rem;\n  color: var(--primary);\n  margin-bottom: 1.5rem;\n  border-bottom: 2px solid var(--accent);\n  display: inline-block;\n  padding-bottom: 0.5rem;\n}\n.benefit-box ul {\n  display: flex;\n  flex-direction: column;\n  gap: 1rem;\n}\n.benefit-box li {\n  font-size: 1.1rem;\n  display: flex;\n  align-items: center;\n  gap: 0.75rem;\n}\n.check-icon {\n  color: var(--success);\n  font-weight: bold;\n  font-size: 1.25rem;\n}`,

  'components/Footer.jsx': `import React from 'react';\nimport './Footer.css';\n\nconst Footer = () => {\n  return (\n    <footer className="footer">\n      <div className="container">\n        <div className="footer-content">\n          <div className="footer-brand">\n            <div className="logo text-white">SkillBridge</div>\n            <p>Empowering the next generation of talent.</p>\n          </div>\n        </div>\n        <div className="footer-bottom">\n          <p>&copy; 2024 SkillBridge. All rights reserved.</p>\n        </div>\n      </div>\n    </footer>\n  );\n};\n\nexport default Footer;`,
  'components/Footer.css': `.footer {\n  background-color: var(--primary);\n  color: white;\n  padding: 4rem 0 2rem;\n}\n.footer-content {\n  margin-bottom: 3rem;\n}\n.footer-brand .logo {\n  color: white;\n  font-size: 2rem;\n  margin-bottom: 1rem;\n}\n.footer-brand p {\n  color: #94a3b8;\n}\n.footer-bottom {\n  border-top: 1px solid #1e293b;\n  padding-top: 2rem;\n  text-align: center;\n  color: #94a3b8;\n}`,

  // --- PAGES ---
  'pages/Home.jsx': `import React from 'react';\nimport Hero from '../components/Hero';\nimport HowItWorks from '../components/HowItWorks';\nimport Categories from '../components/Categories';\nimport WhySkillBridge from '../components/WhySkillBridge';\nimport FeaturedProjects from '../components/FeaturedProjects';\nimport Benefits from '../components/Benefits';\n\nconst Home = () => {\n  return (\n    <>\n      <Hero />\n      <HowItWorks />\n      <Categories />\n      <WhySkillBridge />\n      <FeaturedProjects />\n      <Benefits />\n    </>\n  );\n};\n\nexport default Home;`,
  
  'pages/Login.jsx': `import React from 'react';\nimport { Link } from 'react-router-dom';\nimport './Auth.css';\n\nconst Login = () => {\n  return (\n    <div className="auth-page">\n      <div className="auth-container">\n        <h2>Welcome Back</h2>\n        <p className="auth-subtitle">Login to your SkillBridge account</p>\n        <form className="auth-form">\n          <div className="form-group">\n            <label>Email Address</label>\n            <input type="email" placeholder="Enter your email" />\n          </div>\n          <div className="form-group">\n            <label>Password</label>\n            <input type="password" placeholder="Enter your password" />\n          </div>\n          <div className="form-options">\n            <label className="checkbox-label">\n              <input type="checkbox" /> Remember me\n            </label>\n            <a href="#" className="forgot-password">Forgot Password?</a>\n          </div>\n          <button type="submit" className="btn btn-primary w-full">Login</button>\n        </form>\n        <p className="auth-footer">\n          Don't have an account? <Link to="/register">Register here</Link>\n        </p>\n      </div>\n    </div>\n  );\n};\n\nexport default Login;`,

  'pages/Register.jsx': `import React, { useState } from 'react';\nimport { Link } from 'react-router-dom';\nimport './Auth.css';\n\nconst Register = () => {\n  const [accountType, setAccountType] = useState('student');\n\n  return (\n    <div className="auth-page">\n      <div className="auth-container">\n        <h2>Create an Account</h2>\n        <p className="auth-subtitle">Join SkillBridge today</p>\n        \n        <div className="account-type-toggle">\n          <button \n            className={\`toggle-btn \${accountType === 'student' ? 'active' : ''}\`} \n            onClick={() => setAccountType('student')}\n          >Student</button>\n          <button \n            className={\`toggle-btn \${accountType === 'company' ? 'active' : ''}\`} \n            onClick={() => setAccountType('company')}\n          >Company</button>\n        </div>\n\n        <form className="auth-form">\n          <div className="form-group">\n            <label>Full Name {accountType === 'company' && '/ Company Name'}</label>\n            <input type="text" placeholder="Enter name" />\n          </div>\n          <div className="form-group">\n            <label>Email Address</label>\n            <input type="email" placeholder="Enter email" />\n          </div>\n          <div className="form-group">\n            <label>Password</label>\n            <input type="password" placeholder="Create password" />\n          </div>\n          <button type="submit" className="btn btn-primary w-full">Register</button>\n        </form>\n        <p className="auth-footer">\n          Already have an account? <Link to="/login">Login here</Link>\n        </p>\n      </div>\n    </div>\n  );\n};\n\nexport default Register;`,
  
  'pages/Auth.css': `.auth-page {\n  min-height: calc(100vh - 80px);\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  background-color: var(--background);\n  padding: 2rem;\n}\n.auth-container {\n  background-color: var(--surface);\n  padding: 3rem;\n  border-radius: var(--radius-lg);\n  box-shadow: var(--shadow-lg);\n  width: 100%;\n  max-width: 480px;\n  border: 1px solid var(--border);\n}\n.auth-container h2 {\n  color: var(--primary);\n  font-size: 2rem;\n  margin-bottom: 0.5rem;\n  text-align: center;\n}\n.auth-subtitle {\n  color: var(--text-secondary);\n  text-align: center;\n  margin-bottom: 2rem;\n}\n.auth-form {\n  display: flex;\n  flex-direction: column;\n  gap: 1.5rem;\n}\n.form-group {\n  display: flex;\n  flex-direction: column;\n  gap: 0.5rem;\n}\n.form-group label {\n  font-weight: 500;\n  color: var(--text);\n}\n.form-group input {\n  padding: 0.75rem 1rem;\n  border: 1px solid var(--border);\n  border-radius: var(--radius-md);\n  font-family: inherit;\n  font-size: 1rem;\n  transition: border-color 0.2s;\n}\n.form-group input:focus {\n  outline: none;\n  border-color: var(--primary);\n}\n.form-options {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  font-size: 0.9rem;\n}\n.forgot-password {\n  color: var(--secondary);\n  font-weight: 500;\n}\n.auth-footer {\n  margin-top: 2rem;\n  text-align: center;\n  color: var(--text-secondary);\n}\n.auth-footer a {\n  color: var(--primary);\n  font-weight: 600;\n}\n.account-type-toggle {\n  display: flex;\n  background-color: var(--background);\n  border-radius: var(--radius-md);\n  padding: 0.25rem;\n  margin-bottom: 2rem;\n}\n.toggle-btn {\n  flex: 1;\n  padding: 0.5rem;\n  border-radius: var(--radius-sm);\n  font-weight: 500;\n  color: var(--text-secondary);\n  transition: all 0.2s;\n}\n.toggle-btn.active {\n  background-color: var(--surface);\n  color: var(--primary);\n  box-shadow: var(--shadow-sm);\n}`,
};

for (const [filename, content] of Object.entries(files)) {
  fs.writeFileSync(path.join(srcDir, filename), content);
}
console.log('Files generated successfully.');
